stages:
  train:
    cmd: python src/train.py
    deps:
    - data/raw
    - src/train.py
    params:
    - train.epochs
    - train.lr
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
