train:
  lr: 0.001
  epochs: 30
  batch_size: 16
  img_size: 224
  validation_split: 0.2
  testing_split: 0.1
  seed: 42
  dataset_dir: data/augmented
  base_weights: imagenet
  online_augmentation: false

augment:
  input_dir: data/raw
  output_dir: data/augmented
  img_size: 224
  copies_per_image: 1
  include_original: true
  seed: 42
